// Generated by https://quicktype.io

import 'package:peliculas/src/models/actores_model.dart';

class CastBuscado {
  List<ActorBuscado> actorBuscado = new List();
  CastBuscado.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;

    jsonList.forEach((item) {
      final actor = ActorBuscado.fromJsonMap(item);
      actorBuscado.add(actor);
    });
  }
}

class ActorBuscado extends Actor {
  String uniqueId;
  double popularity;
  String knownForDepartment;
  String name;
  int id;
  String profilePath;
  bool adult;
  List<dynamic> knownFor;
  int gender;

  ActorBuscado({
    this.popularity,
    this.knownForDepartment,
    this.name,
    this.id,
    this.profilePath,
    this.adult,
    this.knownFor,
    this.gender,
  });

  ActorBuscado.fromJsonMap(Map<String, dynamic> json) {
    popularity = json['popularity'];
    knownForDepartment = json['known_for_department'];
    name = json['name'];
    id = json['id'];
    profilePath = json['profile_path'];
    adult = json['adult'];
    knownFor = json['known_for'];
    gender = json['gender'];
  }

  getFoto() {
    if (profilePath == null) {
      return 'https://res.cloudinary.com/kikesan/image/upload/v1578437124/peliculasApp/uywisicoxtk8ruovc8qp.png';
    } else {
      return 'https://image.tmdb.org/t/p/w500/$profilePath';
    }
  }
}
