// Generated by https://quicktype.io

import 'package:peliculas/src/models/pelicula_model.dart';

class Series {
  List<Serie> items = new List();
  Series();
  Series.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;

    for (var item in jsonList) {
      final serie = new Serie.fromJsonMap(item);
      items.add(serie);
    }
  }
}

class Serie {
  String uniqueId; //creado para evitar conflicto en hero

  double popularity;
  int voteCount;
  String posterPath;
  int id;
  String backdropPath;
  String originalLanguage;
  String originalName;
  List<int> genreIds;
  String name;
  List<dynamic> originCountry;
  double voteAverage;
  String overview;
  String firstAirDate;

  Serie({
    this.originalName,
    this.genreIds,
    this.name,
    this.popularity,
    this.originCountry,
    this.voteCount,
    this.firstAirDate,
    this.backdropPath,
    this.originalLanguage,
    this.id,
    this.voteAverage,
    this.overview,
    this.posterPath,
  });

  Serie.fromJsonMap(Map<String, dynamic> json) {
    originalName = json['original_name'];
    genreIds = json['genre_ids'].cast<int>();
    name = json['name'];
    popularity = json['popularity'] / 1;
    originCountry = json['origin_country'];
    voteCount = json['vote_count'];
    firstAirDate = json['first_air_date'];
    backdropPath = json['backdrop_path'];
    originalLanguage = json['original_language'];
    id = json['id'];
    voteAverage = json['vote_average'] / 1;
    overview = json['overview'];
    posterPath = json['poster_path'];
  }

  getPosterImg() {
    if (posterPath == null) {
      return 'https://dakotamoda.es/wp-content/themes/gecko/assets/images/placeholder.png';
    } else {
      return 'https://image.tmdb.org/t/p/w500/$posterPath';
    }
  }

  getBackgroundImg() {
    if (backdropPath == null) {
      return 'https://dakotamoda.es/wp-content/themes/gecko/assets/images/placeholder.png';
    } else {
      return 'https://image.tmdb.org/t/p/w500$backdropPath';
    }
  }
}
